### ISSUE TITLE
a.game is undefined

### ISSUE THREAD

**Issue by OkijinLtd** [BuongiornoMIP/GamifiveSDK#10]
I am currently trying to update the SDK but I hit an issue everytime with an error occurring in your API files:
 
http://s.motime.com/js/wl/webstore_html5game/gfsdk/dist/gfsdk.min.js
http://s.motime.com/js/wl/webstore_html5game/gfsdk/dist/gfsdk.js

<img width="324" alt="error" src="https://cloud.githubusercontent.com/assets/5784508/11243324/b6ea32e4-8e4a-11e5-8a15-70a4cee536f6.png">

**Comment by ffognani** [comment]
Hi, is GamifiveSDK.init called with debug: false (or without debug parameter)?

**Comment by OkijinLtd** [comment]
We call it like this:
    GamifiveSDK.init({
        lite: true
    });

**Comment by ffognani** [comment]
If you test your game outside Gamifive's environment (and from the screenshot it seems that you're testing it locally on your pc) you must set debug: true otherwise GamifiveSDK will try to use some API that are unreachable outside Gamifive.

Use:
GamifiveSDK.init({
    lite: true,
    debug: true
}); 
when testing on your environment and remember to set debug: false when you upload your package on Gamifive.

Thank you!

**Comment by OkijinLtd** [comment]
Seems to have done the trick, all working now thanks!
